"""empty message

Revision ID: 09d8d40b8e11
Revises: 613c27b85f9f
Create Date: 2023-04-15 22:00:57.101311

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "09d8d40b8e11"
down_revision = "613c27b85f9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_tag_association",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_tag_association")
    # ### end Alembic commands ###
