"""empty message

Revision ID: 613c27b85f9f
Revises: cce37e30c091
Create Date: 2023-04-15 21:56:04.856915

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "613c27b85f9f"
down_revision = "cce37e30c091"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    # ### end Alembic commands ###
